version: 2.1

orbs:
  rn: react-native-community/react-native@dev:0.1.0-rc3

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  analyse:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run validate:eslint
      - run:
          name: Flow
          command: yarn run validate:flow
      - run:
          name: TypeScript
          command: yarn run validate:typescript
      - run:
          name: Jest
          command: yarn run test:jest
      - run:
          name: Build Android JavaScript Bundle
          command: yarn run test:detox:android:bundle:release
      - run:
          name: Build iOS JavaScript Bundle
          command: yarn run test:detox:ios:bundle:release
      - persist_to_workspace:
          root: .
          paths:
            - .tmp
  build_android_debug:
    executor: rn/linux_android
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - rn/android_build:
          project_path: "example/android"
          build_type: debug
      - persist_to_workspace:
          root: .
          paths:
            - example/android/app/build/outputs/apk
  build_android_release:
    executor: rn/linux_android
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - rn/android_build:
          project_path: "example/android"
          build_type: release
      - persist_to_workspace:
          root: .
          paths:
            - example/android/app/build/outputs/apk
  test_android_e2e:
    executor: rn/macos
    steps:
      - attach_workspace:
          at: .
      - rn/setup_macos_executor
      - rn/yarn_install
      - rn/android_emulator_start
      # TODO: Make this a command
      - run:
          name: Run Detox Tests
          command: yarn run test:detox:android:test:release
  test_ios_e2e:
    executor: rn/macos
    steps:
      - attach_workspace:
          at: .
      - rn/setup_macos_executor
      - rn/ios_simulator_start
      - rn/yarn_install
      # TODO: Make this a command
      - restore_cache:
          key: v1-ios-build-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json" }}
      - run:
          name: Build iOS Testing App
          command: yarn run test:detox:ios:build:release
      - save_cache:
          paths:
            - ~/project/example/ios/build/Build
          key: v1-ios-build-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json" }}
          when: always
      # TODO: Make this a command
      - run:
          name: Run Detox Tests
          command: yarn run test:detox:ios:test:release
  publish:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Publish to NPM
          command: yarn ci:publish

workflows:
  test:
    jobs:
      - checkout_code
      # - analyse:
      #     requires:
      #       - checkout_code
      # - build_android_debug:
      #     requires:
      #       - analyse
      - build_android_release:
          requires:
            - checkout_code
            # - analyse
      - test_android_e2e:
          requires:
            - build_android_release
      # - test_ios_e2e:
      #     requires:
      #       - analyse
      # - publish:
      #     requires:
      #       - analyse
      #       - test_android_e2e
      #       - test_ios_e2e
      #     filters:
      #       branches:
      #         only: master
